import tailwindcss from '@tailwindcss/vite'
import { readFileSync } from 'node:fs'
import { defineConfig } from 'wxt'

const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf-8'))

const ICON_SIZES = [16, 32, 48, 64, 128] as const

// Full-resolution icon injected into the page UI (floating button).
const PAGE_ICON_PATH = '/icon.png'

// Icons generated by @wxt-dev/auto-icons for the manifest/toolbar, resized per entry.
const manifestIconMap = Object.fromEntries(ICON_SIZES.map((size) => [size, `/icons/${size}.png`])) as Record<
  (typeof ICON_SIZES)[number],
  string
>

function versions() {
  return {
    version: process.env.EXTENSION_VERSION ?? pkg.version,
    ...(process.env.EXTENSION_VERSION_NAME && {
      version_name: process.env.EXTENSION_VERSION_NAME,
    }),
  }
}

export default defineConfig({
  modules: ['@wxt-dev/module-react', '@wxt-dev/auto-icons'],
  autoIcons: {
    sizes: [...ICON_SIZES],
  },
  vite: () => ({
    plugins: [tailwindcss()],
  }),
  webExt: {
    binaries: {
      edge: String.raw`C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`,
    },
  },
  srcDir: 'src',
  manifest: () => ({
    name: 'FID Plus',
    description: 'Painel flutuante com ganhos semanais, objetivos e marcos do Football Identity.',
    action: {
      default_icon: manifestIconMap,
    },
    web_accessible_resources: [
      {
        matches: ['*://*.footballidentity.org/*'],
        resources: [PAGE_ICON_PATH],
      },
    ],
    browser_specific_settings: {
      gecko: {
        id: 'fid-plus@marcelotk15.github.io',
        data_collection_permissions: {
          required: ['none'],
        },
      },
    },
    ...versions(),
  }),
})
