export const SAMPLE_WEEKLY_OBJECTIVES_PAYLOAD = {
  objectives: [
    {
      completed_at: '2026-06-29T03:22:19.93785+00:00',
      reward_money: 1000,
      target_count: 1,
      current_count: 1,
      objective_key: 'perfect_minigame_score_week',
    },
    {
      completed_at: '2026-06-29T23:51:56.051206+00:00',
      reward_money: 500,
      target_count: 2,
      current_count: 2,
      objective_key: 'vote_2_mvps',
    },
    {
      completed_at: '2026-06-29T23:52:47.579606+00:00',
      reward_money: 500,
      target_count: 2,
      current_count: 2,
      objective_key: 'watch_2_replays',
    },
    {
      completed_at: '2026-07-03T03:44:11.908131+00:00',
      reward_money: 700,
      target_count: 15,
      current_count: 15,
      objective_key: 'play_15_minigames_week',
    },
    {
      completed_at: null,
      reward_money: 1000,
      target_count: 7,
      current_count: 5,
      objective_key: 'complete_dailies_perfect',
    },
    {
      completed_at: null,
      reward_money: 500,
      target_count: 2,
      current_count: 1,
      objective_key: 'play_2_league_matches',
    },
    {
      completed_at: null,
      reward_money: 500,
      target_count: 2,
      current_count: 1,
      objective_key: 'play_2_pickup_matches',
    },
    {
      completed_at: null,
      reward_money: 500,
      target_count: 1,
      current_count: 0,
      objective_key: 'team_training_week',
    },
    {
      completed_at: null,
      reward_money: 500,
      target_count: 14,
      current_count: 13,
      objective_key: 'train_14_attributes',
    },
    {
      completed_at: null,
      reward_money: 500,
      target_count: 3,
      current_count: 0,
      objective_key: 'use_daily_shop_3x',
    },
  ],
  week_start: '2026-06-29',
  completed_count: 4,
  milestone_5_credited: false,
  milestone_10_credited: false,
} as const
